config/routes.rb
BulletinBoard::Application.routes.draw do

  root to: "home#index"
 
  devise_for :users

  resources :advertisements, except: :show

  resources :categories, only: :show

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  attr_accessible :address, :city, :description, :email, :image, :title, :category_id

  belongs_to :category

  validates_presence_of :address, :city, :description, :email, :title
  validates :title, length: { maximum: 50 }
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title

  has_many :advertisements

  validates :title, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
  # attr_accessible :title, :body

  ROLES = %w[admin advertiser]

  def admin?
    self.role == "admin"
  end

end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :new, :create]
  before_filter :authorize, except: [:index, :new, :create]

  def index
    @advertisements = Advertisement.order('created_at DESC')
    @categories = Category.all

    respond_to do |format|
      format.html
    end
  end

  def new
    @advertisement = Advertisement.new

    respond_to do |format|
      format.html
    end
  end

  def create
    @advertisement = Advertisement.new(params[:advertisement])

    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to advertisements_url, notice: "Advertisement has been successfully created" }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
    @advertisement = Advertisement.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def update
    @advertisement = Advertisement.find(params[:id])

    respond_to do |format|
      if @advertisement.update_attributes(params[:advertisement])
        format.html { redirect_to advertisements_url, notice: "Advertisement has been successfully updated" }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    @advertisement = Advertisement.find(params[:id])
    @advertisement.destroy

    respond_to do |format|
      format.html { redirect_to advertisements_url }
    end     
  end

  private

  def authorize
    unless user_signed_in? && current_user.admin?
      redirect_to advertisements_url, alert: "Unauthorized access"      
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a? User
      advertisements_path
    else
      super
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @advertisements = @category.advertisements.order("created_at DESC")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/advertisements/_form.html.haml
= semantic_form_for @advertisement do |f|
  = f.inputs do
    = f.input :title
    = f.input :image
    = f.input :description, input_html: { rows: 5 }
    = f.input :email
    = f.input :city
    = f.input :address
    = f.input :category
  = f.actions do
    = f.action :submit, button_html: { class: 'btn btn-primary'}
    = f.action :cancel

app/views/advertisements/edit.html.haml
%h1 Edit advertisement
= render 'form'

app/views/advertisements/index.html.haml
.span3
  .well.sidebar-nav
    %ul.nav.nav-list
      %li.nav-header Categories
      - @categories.each do |category|
        %li= link_to category.title, category_path(category)
.span9
  %h1.center Advertisements
  = bootstrap_flash
  .advertisements
    - model_class = Advertisement
    %table.table.table-hover
      %thead
        %tr
          %th= model_class.human_attribute_name(:title)
          %th= model_class.human_attribute_name(:email)
          %th= model_class.human_attribute_name(:created_at)
      %tbody
        - @advertisements.each do |advertisement|
          %tr
            %td
              %p= advertisement.title
            %td
              %p= advertisement.email
            %td
              %p= advertisement.created_at.strftime("%b %d, %H:%M")
            - if user_signed_in? && current_user.admin?
              %td
                = link_to "Edit", edit_advertisement_path(advertisement), class: 'btn btn-mini'              
                = link_to "Destroy", advertisement_path(advertisement), :method => :delete, class: 'btn btn-mini btn-danger'
    .center
      =link_to "New Advertisement", new_advertisement_path, class: 'btn btn-primary'

app/views/advertisements/new.html.haml
%h1 Create new advertisement
= render 'form'

app/views/categories/show.html.haml
.span12
  = bootstrap_flash
  .advertisements  
    - model_class = Advertisement
    %table.table.table-hover
      %thead
        %tr
          %th= model_class.human_attribute_name(:title)
          %th= model_class.human_attribute_name(:email)
          %th.pull-right= model_class.human_attribute_name(:created_at)
      %tbody
        - @advertisements.each do |advertisement|
          %tr
            %td
              %p= advertisement.title
            %td
              %p= advertisement.email
            %td
              %p.pull-right= advertisement.created_at.strftime("%b %d, %H:%M")

app/views/home/index.html.haml
.span12
  = bootstrap_flash
  .well.center
    %h1 Welcome to Bulletin Board
    = link_to "Browse advertisements", advertisements_path, class: 'btn btn-primary btn-large'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BulletinBoard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BulletinBoard"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "BulletinBoard", root_path, class: 'brand'
          .container.nav-collapse
            - if user_signed_in?
              %ul.nav              
                %li= link_to "Sign Out", destroy_user_session_path, method: :delete
              %ul.nav.pull-right
                %li.auth-info= "Welcome, #{current_user.email}"
            - else
              %ul.nav              
                %li= link_to "Sign In", new_user_session_path
                %li= link_to "Sign Up", new_user_registration_path
              %ul.nav.pull-right
                %li.auth-info= "Welcome, Guest"             

    .container

      .row
        = yield

    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"